import "./globals.css";
import { Inter } from "next/font/google";

export const metadata = {
  title: "Images IA",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title> X Prodia Image Generation </title>
      </head>
      <body className="bg-[#171717]   bg-no-repeat min-h-screen">
        {children}
      </body>
    </html>
  );
}
